---
- name: "Play 1- cgi website configuration"  
  hosts: localhost
  become: yes
  tasks:
   - name: Install a list of packages with a list variable
     yum:
       name: "{{ packages }}"
     vars:
       packages:
       - telnet
       - vim
       - wget


